export const events = [
  {
    id: 1,
    date: "20/09/2024",
    time: "Del 15 de enero al 20 de diciembre de 12:00 a 23:00",
    city: "Cali",
    address: "Movistar Arena",
    img: "https://cdn.eticket.co/imagenes/artistas/240127112302827_performer_img2_CONFIRMACIoN.jpg",
    href: "/detailedevent",
    title: "CARMINA BURANA",
    desc: "Segundo partido de Millonarios en Liga",
  },
  {
    id: 2,
    date: "20/09/2024",
    time: "21:00hrs",
    city: "Bogotá",
    address: "Movistar Arena",
    href: "/detailedevent",
    title: "Concierto de Rock",
    desc: "¡Disfruta de una noche llena de música rock en vivo!",
  },
  {
    id: 3,
    date: "20/09/2024",
    time: "22:00hrs",
    city: "Medellin",
    address: "Movistar Arena",
    href: "/detailedevent",
    title: "Evento Cultural",
    desc: "Descubre y celebra la diversidad cultural de la ciudad.",
  },
  {
    id: 4,
    date: "20/09/2024",
    time: "19:00hrs",
    city: "Barranquilla",
    address: "Movistar Arena",
    href: "/detailedevent",
    title: "Conferencia Inspiradora",
    desc: "Una conferencia que te dejará pensando y motivado.",
  },
  {
    id: 5,
    date: "20/09/2024",
    time: "20:00hrs",
    city: "Bogotá",
    address: "Movistar Arena",
    href: "/detailedevent",
    title: "Concierto de salsa",
    desc: "Marc Anthony viene a la capital",
  },
  {
    id: 6,
    date: "20/09/2024",
    time: "20:30hrs",
    city: "Bogotá",
    address: "Movistar Arena",
    href: "/detailedevent",
    title: "Donde el Ferxxo 2024",
    desc: "Prepárate para iniciar el año perreando con una gran fiesta junto a los mejores temas del Ferxxo en Bogotá.",
  },
  {
    id: 7,
    date: "01/02/2024",
    time: "18:00hrs",
    city: "Bogotá",
    address: "Estadio Nemesio Camacho El Campin",
    href: "/detailedevent",
    title: "Millonarios vs Alianza",
    desc: "Segundo partido de Millonarios en Liga",
  },
  {
    id: 8,
    date: "20/09/2024",
    time: "20:00hrs",
    city: "Bogotá",
    address: "Movistar Arena",
    href: "/detailedevent",
    title: "The Mills en Sánchez, Bogotá 2024",
    desc: "The Mills es una de las bandas más representativas del rock colombiano, desde sus inicios en 2018. Con sus canciones Amor Depredador, Guadalupe, El Amor duele, y su versión de Lobo Hombre en París de la Unión, han tocado en los escenarios más importantes de Colombia, México y recientemente con una gira por Ecuador. Ahora se presentarán el 7 y 8 de Febrero en Sanchez Cervezeria, uno de los mejores escenarios de música en vivo de Bogotá, presentando el show de su nuevo disco “el amor es fácil, las relaciones no”.",
  },
];
